services:
  openhands:
    build:
      context: /Users/leecarlin/OpenHands
      dockerfile: /Users/leecarlin/OpenHands/containers/app/Dockerfile
    image: openhands:latest
    container_name: openhands-ladybug
    environment:
      - SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:0.40-nikolaik
      - WORKSPACE_MOUNT_PATH=/project
    ports:
      - "3001:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.openhands-state:/.openhands-state
      - /Users/leecarlin/Documents/LadybugRealEstate:/project
    stdin_open: true
    tty: true
