version: "3.8"

services:
  openhands:
    build:
      context: ../OpenHands           # Path to the OpenHands source
      dockerfile: ./containers/app/Dockerfile
    image: openhands:latest
    container_name: openhands-ladybug
    environment:
      - SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:0.40-nikolaik
      - WORKSPACE_MOUNT_PATH=/app
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.openhands-state:/.openhands-state
      - .:/app                       # 👈 Mount LadybugRealEstate folder directly into /app
    pull_policy: build
    stdin_open: true
    tty: true
