# netlify.toml
[build]
  command = "npm install && npx vite build && cp public/_redirects dist/_redirects"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
