# netlify.toml
[build]
  command = "npm ci && npx vite build"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--omit=optional"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
