[build]
  command = "npm install && npm run build"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "20"
  NETLIFY_USE_YARN = "false"
  NPM_CONFIG_PRODUCTION = "false"
  DISABLE_NETLIFY_DEV = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
